#Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#Actuator
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: serviceregistry,health,info
  info:
    env:
      enabled: true

#zipkin
zipkin:
    base-url: http://localhost:9411
    enabled: true
    
#rabbitmq
rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    
#log4j
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

